version: 0.0
os: linux
files:
  - source: HelloWorld.py
    destination: /var/www/html/HelloWorld.py
hooks:
  BeforeInstall:
    - location: python HelloWorld_tst.py
  ApplicationStart:
    - location: python HelloWorld.py
      timeout: 10
