version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: python HelloWorld_tst.py
  ApplicationStart:
    - location: python HelloWorld.py
      timeout: 10
